project:
  type: website
  output-dir: docs
  
website:
  title: "Erik Wojcik"
  page-footer: "Copyright 2023, Erik Wojcik" 
  reader-mode: false
  navbar:
    pinned: true
    left:
      - text: Midterm
        href: DANL310_midterm_Wojcik_Erik.qmd
      - text: Project 
        href: teamproj0.qmd
      - text: Homework
        menu:
          - text: Homework 1
            href: DANL310_hw1_Wojcik_Erik.qmd
          - text: Homework 2
            href: DANL310_hw2_Wojcik_Erik.qmd
          - text: Homework 3
            href: DANL310_hw3_Wojcik_Erik.qmd
            
format:
  html:
    theme:
      light: flatly
      dark: [darkly, theme-dark.scss]
    # mainfont: Georgia, serif;
    # mainfont: Gill Sans, sans-serif;
    toc: true
    include-after-body: target_blank.html


